from typing import Any, Optional, Union

class Redis:
    def __init__(self, **kwargs: Any) -> None: ...
    @classmethod
    def from_url(cls, url: str, **kwargs: Any) -> "Redis": ...
    def hset(
        self,
        name: str,
        key: Optional[str] = None,
        value: Any = None,
        mapping: Optional[dict[str, Any]] = None,
    ) -> int: ...
    def hget(self, name: str, key: str) -> Optional[str]: ...
    def set(self, name: str, value: Union[str, bytes]) -> bool: ...
    def get(self, name: str) -> Optional[str]: ...
    def expire(self, name: str, time: int) -> bool: ...
    def delete(self, *names: str) -> int: ...
    def setex(self, name: str, time: int, value: Union[str, bytes]) -> bool: ...
    def exists(self, *names: str) -> int: ...

__all__ = ["Redis"]
