class Fernet:
    def __init__(self, key: bytes) -> None: ...
    def encrypt(self, data: bytes) -> bytes: ...
    def decrypt(self, token: bytes) -> bytes: ...
    @classmethod
    def generate_key(cls) -> bytes: ...
