from typing import Any

class RequestException(Exception): ...

class exceptions:
    RequestException: type[RequestException]

class Response:
    def json(self) -> Any: ...
    def raise_for_status(self) -> None: ...
    @property
    def headers(self) -> dict[str, str]: ...
    @property
    def status_code(self) -> int: ...

class Session:
    def __init__(self) -> None: ...
    def mount(self, prefix: str, adapter: Any) -> None: ...
    def get(self, url: str, **kwargs: Any) -> Response: ...
    def post(self, url: str, **kwargs: Any) -> Response: ...
    @property
    def headers(self) -> dict[str, str]: ...

def get(url: str, **kwargs: Any) -> Response: ...
def post(url: str, **kwargs: Any) -> Response: ...
