from typing import Any, Callable, Dict, Optional

class APIRouter:
    def __init__(self, prefix: str = "", **kwargs: Any) -> None: ...
    def post(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...
    def get(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...
    def put(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...
    def delete(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...
    def patch(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...

class FastAPI:
    def __init__(
        self,
        title: Optional[str] = None,
        description: Optional[str] = None,
        version: Optional[str] = None,
        **kwargs: Any,
    ) -> None: ...
    def post(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...
    def get(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...
    def put(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...
    def delete(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...
    def patch(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...
    def include_router(self, router: APIRouter, **kwargs: Any) -> None: ...

class Response:
    def __init__(
        self,
        content: Any = None,
        status_code: int = 200,
        headers: Optional[Dict[str, str]] = None,
        media_type: Optional[str] = None,
        **kwargs: Any,
    ) -> None: ...
    @property
    def headers(self) -> Any: ...

class Request:
    def __init__(self, **kwargs: Any) -> None: ...
    @property
    def headers(self) -> Dict[str, str]: ...
    @property
    def query_params(self) -> Dict[str, str]: ...
    @property
    def url(self) -> Any: ...
    @property
    def method(self) -> str: ...
    @property
    def scope(self) -> Dict[str, Any]: ...
    @property
    def client(self) -> Any: ...
    @property
    def cookies(self) -> Dict[str, str]: ...
    async def body(self) -> bytes: ...
