from typing import Any, Callable, Dict, Optional

class FastAPI:
    def __init__(
        self,
        title: Optional[str] = None,
        description: Optional[str] = None,
        version: Optional[str] = None,
        **kwargs: Any,
    ) -> None: ...
    def post(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...
    def get(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...
    def put(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...
    def delete(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...
    def patch(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...

class Request:
    def __init__(self, **kwargs: Any) -> None: ...
    @property
    def headers(self) -> Dict[str, str]: ...
    @property
    def query_params(self) -> Dict[str, str]: ...
    @property
    def url(self) -> Any: ...
    @property
    def method(self) -> str: ...
    async def body(self) -> bytes: ...
