from typing import Dict, List, Optional

class MutableHeaders:
    def __init__(self, headers: Optional[Dict[str, str]] = None) -> None: ...
    def __getitem__(self, key: str) -> str: ...
    def __setitem__(self, key: str, value: str) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def get(self, key: str, default: Optional[str] = None) -> Optional[str]: ...
    def append(self, key: str, value: str) -> None: ...
    def items(self) -> List[tuple[str, str]]: ...
    def keys(self) -> List[str]: ...
    def values(self) -> List[str]: ...
