from typing import Any, Protocol

class Client(Protocol):
    def get_caller_identity(self) -> dict[str, Any]: ...
    def get_parameter(self, *, Name: str, WithDecryption: bool) -> dict[str, Any]: ...
    def get_parameters(
        self, *, Names: list[str], WithDecryption: bool
    ) -> dict[str, Any]: ...
    def put_parameter(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_paginator(self, operation_name: str) -> Any: ...
    def get_waiter(self, waiter_name: str) -> Any: ...
    def create_policy(self, **kwargs: Any) -> dict[str, Any]: ...
    def create_policy_version(self, **kwargs: Any) -> dict[str, Any]: ...
    def list_policy_versions(self, *, PolicyArn: str) -> dict[str, Any]: ...
    def delete_policy_version(
        self, *, PolicyArn: str, VersionId: str
    ) -> dict[str, Any]: ...
    def get_role(self, *, RoleName: str) -> dict[str, Any]: ...
    def create_role(self, **kwargs: Any) -> dict[str, Any]: ...
    def attach_role_policy(self, **kwargs: Any) -> dict[str, Any]: ...
    def put_role_policy(self, **kwargs: Any) -> dict[str, Any]: ...
    def list_attached_role_policies(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_function(self, *, FunctionName: str) -> dict[str, Any]: ...
    def get_function_configuration(self, *, FunctionName: str) -> dict[str, Any]: ...
    def create_function(self, **kwargs: Any) -> dict[str, Any]: ...
    def update_function_code(self, **kwargs: Any) -> dict[str, Any]: ...
    def update_function_configuration(self, **kwargs: Any) -> dict[str, Any]: ...
    def publish_layer_version(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_apis(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_api(self, *, ApiId: str) -> dict[str, Any]: ...
    def update_api(self, *, ApiId: str, **kwargs: Any) -> dict[str, Any]: ...
    def create_api(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_stage(self, *, ApiId: str, StageName: str) -> dict[str, Any]: ...
    def get_stages(self, *, ApiId: str, **kwargs: Any) -> dict[str, Any]: ...
    def update_stage(self, **kwargs: Any) -> dict[str, Any]: ...
    def create_stage(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_integrations(self, **kwargs: Any) -> dict[str, Any]: ...
    def create_integration(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_routes(self, **kwargs: Any) -> dict[str, Any]: ...
    def create_route(self, **kwargs: Any) -> dict[str, Any]: ...
    def update_route(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_route(self, *, ApiId: str, RouteId: str) -> dict[str, Any]: ...
    def add_permission(self, **kwargs: Any) -> dict[str, Any]: ...
    def invoke(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_policy(self, **kwargs: Any) -> dict[str, Any]: ...
    # S3 methods
    def head_bucket(self, *, Bucket: str) -> dict[str, Any]: ...
    def create_bucket(self, *, Bucket: str, **kwargs: Any) -> dict[str, Any]: ...
    def put_bucket_versioning(
        self, *, Bucket: str, VersioningConfiguration: dict[str, Any]
    ) -> dict[str, Any]: ...
    def put_public_access_block(
        self, *, Bucket: str, PublicAccessBlockConfiguration: dict[str, Any]
    ) -> dict[str, Any]: ...
    def put_bucket_encryption(
        self, *, Bucket: str, ServerSideEncryptionConfiguration: dict[str, Any]
    ) -> dict[str, Any]: ...
    def put_bucket_policy(self, *, Bucket: str, Policy: str) -> dict[str, Any]: ...
    def put_bucket_lifecycle_configuration(
        self, *, Bucket: str, LifecycleConfiguration: dict[str, Any]
    ) -> dict[str, Any]: ...
    def put_bucket_tagging(
        self, *, Bucket: str, Tagging: dict[str, Any]
    ) -> dict[str, Any]: ...
    def put_object(
        self, *, Bucket: str, Key: str, Body: bytes, **kwargs: Any
    ) -> dict[str, Any]: ...
    def list_object_versions(
        self, *, Bucket: str, Prefix: str, **kwargs: Any
    ) -> dict[str, Any]: ...
    # ACM methods
    def request_certificate(
        self, *, DomainName: str, ValidationMethod: str, **kwargs: Any
    ) -> dict[str, Any]: ...
    def describe_certificate(self, *, CertificateArn: str) -> dict[str, Any]: ...
    # API Gateway v2 methods
    def get_domain_name(self, *, DomainName: str) -> dict[str, Any]: ...
    def create_domain_name(
        self, *, DomainName: str, **kwargs: Any
    ) -> dict[str, Any]: ...
    def update_domain_name(
        self, *, DomainName: str, **kwargs: Any
    ) -> dict[str, Any]: ...
    def get_api_mappings(self, *, DomainName: str, **kwargs: Any) -> dict[str, Any]: ...
    def create_api_mapping(
        self, *, DomainName: str, ApiId: str, Stage: str, **kwargs: Any
    ) -> dict[str, Any]: ...
    def update_api_mapping(
        self,
        *,
        ApiMappingId: str,
        DomainName: str,
        ApiId: str,
        Stage: str,
        **kwargs: Any,
    ) -> dict[str, Any]: ...

class Session:
    def __init__(self, **kwargs: Any) -> None: ...
    def client(self, service_name: str, **kwargs: Any) -> Client: ...

def client(service_name: str, **kwargs: Any) -> Client: ...
