from typing import Any

class LambdaClient:
    def create_function(
        self,
        FunctionName: str,
        Runtime: str,
        Role: str,
        Handler: str,
        Code: dict[str, Any],
        Description: str | None = None,
        Timeout: int | None = None,
        MemorySize: int | None = None,
        Publish: bool | None = None,
        VpcConfig: dict[str, Any] | None = None,
        DeadLetterConfig: dict[str, Any] | None = None,
        Environment: dict[str, Any] | None = None,
        KMSKeyArn: str | None = None,
        TracingConfig: dict[str, Any] | None = None,
        Tags: dict[str, str] | None = None,
        Layers: list[str] | None = None,
        FileSystemConfigs: list[dict[str, Any]] | None = None,
        ImageConfig: dict[str, Any] | None = None,
        CodeSigningConfigArn: str | None = None,
        Architectures: list[str] | None = None,
        EphemeralStorage: dict[str, Any] | None = None,
        SnapStart: dict[str, Any] | None = None,
        LoggingConfig: dict[str, Any] | None = None,
    ) -> dict[str, Any]: ...
    def get_function(self, FunctionName: str) -> dict[str, Any]: ...
    def update_function_code(
        self,
        FunctionName: str,
        ZipFile: bytes | None = None,
        S3Bucket: str | None = None,
        S3Key: str | None = None,
        S3ObjectVersion: str | None = None,
        ImageUri: str | None = None,
        Publish: bool | None = None,
        DryRun: bool | None = None,
        RevisionId: str | None = None,
    ) -> dict[str, Any]: ...
    def update_function_configuration(
        self,
        FunctionName: str,
        Role: str | None = None,
        Handler: str | None = None,
        Description: str | None = None,
        Timeout: int | None = None,
        MemorySize: int | None = None,
        VpcConfig: dict[str, Any] | None = None,
        Environment: dict[str, Any] | None = None,
        Runtime: str | None = None,
        DeadLetterConfig: dict[str, Any] | None = None,
        KMSKeyArn: str | None = None,
        TracingConfig: dict[str, Any] | None = None,
        RevisionId: str | None = None,
        Layers: list[str] | None = None,
        FileSystemConfigs: list[dict[str, Any]] | None = None,
        ImageConfig: dict[str, Any] | None = None,
        EphemeralStorage: dict[str, Any] | None = None,
        SnapStart: dict[str, Any] | None = None,
        LoggingConfig: dict[str, Any] | None = None,
        Architectures: list[str] | None = None,
    ) -> dict[str, Any]: ...
    def get_function_configuration(self, FunctionName: str) -> dict[str, Any]: ...
    def publish_layer_version(
        self,
        LayerName: str,
        Content: dict[str, Any],
        Description: str | None = None,
        CompatibleRuntimes: list[str] | None = None,
        LicenseInfo: str | None = None,
        CompatibleArchitectures: list[str] | None = None,
    ) -> dict[str, Any]: ...
