from typing import Dict, Iterator, List, Optional, Tuple, Union

class Headers:
    def __init__(
        self, headers: Union[Dict[str, str], List[Tuple[str, str]], None] = None
    ) -> None: ...
    def get(self, key: str, default: Optional[str] = None) -> Optional[str]: ...
    def items(self) -> Iterator[Tuple[str, str]]: ...
    def keys(self) -> Iterator[str]: ...
    def values(self) -> Iterator[str]: ...
    def __getitem__(self, key: str) -> str: ...
    def __setitem__(self, key: str, value: str) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...

__all__ = ["Headers"]
