import os

import boto3
from botocore.exceptions import ClientError

from aws_config_manager import create_logger

logger = create_logger(log_level="INFO", logger_name="aws_deployment")


class ParameterManager:
    def __init__(
        self,
        parameters: list[dict[str, str | bool]],
        upsert_to_aws: bool = True,
        region: str = "us-east-1",
    ):
        self.parameters = parameters
        self.upsert_to_aws = upsert_to_aws
        if upsert_to_aws:
            self.ssm = boto3.client("ssm", region_name=region)
        else:
            self.ssm = None

    def _set_env_vars(self) -> list[str]:
        params_to_check = []
        export_commands = []
        logger.info("Setting parameters in python enviornment")
        for p in self.parameters:
            key = p["Name"]
            assert isinstance(key, str), f"Key for {key} is not a string"

            key_upper = key.split("/")[-1].upper()
            value = str(p["Value"])
            assert isinstance(key_upper, str), f"Key for {key} is not a string"
            assert isinstance(value, str), f"Value for {key} is not a string"

            existing_key = os.getenv(key_upper)
            if existing_key and existing_key != value:
                logger.warning(
                    f"Enviornment variable aleady exists with {key_upper} as {existing_key}"
                )
                params_to_check.append(key)

            logger.debug(f"Setting {key_upper} to {value} in python enviornment")
            os.environ[key_upper] = str(value)

            # Collect export command for shell script
            export_commands.append(f"export {key_upper}={value}")

        return export_commands

    def _write_shell_script(
        self, export_commands: list[str], script_path: str = "set_env_vars.sh"
    ) -> None:
        """Write export commands to a shell script file."""
        if not export_commands:
            logger.info("No export commands to write to shell script")
            return

        logger.info(f"Writing {len(export_commands)} export commands to {script_path}")

        with open(script_path, "w") as f:
            f.write("#!/bin/bash\n")
            f.write("# Environment variables export script\n")
            f.write("# Generated by ParameterManager\n\n")
            for command in export_commands:
                f.write(f"{command}\n")

        # Make the script executable
        os.chmod(script_path, 0o755)
        logger.info(f"To apply these environment variables, run: source {script_path}")

    def _upload_to_ssm(self, param: dict[str, str | bool]) -> None:
        if self.ssm is None:
            logger.warning(f"Skipping upload to SSM for {param['Name']}")
            return

        # Ensure parameter name starts with / for SSM
        param_name = str(param["Name"])
        if not param_name.startswith("/"):
            param_name = f"/{param_name}"
            logger.info(f"Correcting parameter name to {param_name}")
            param = param.copy()  # Create a copy to avoid modifying the original
            param["Name"] = param_name

        logger.info(f"Uploading parameter {param['Name']} to SSM")
        self.ssm.put_parameter(**param)
        return

    def _set_aws_parameters(self) -> None:
        logger.info("Setting parameters in AWS SSM")
        try:
            for param in self.parameters:
                self._upload_to_ssm(param)
            return
        except ClientError as e:
            raise ClientError(f"AWS error: {e}") from e
        except Exception as e:
            raise Exception(f"Unexpected error: {e}") from e

    def deploy(self, script_path: str = "set_env_vars.sh") -> None:
        logger.info("Processing parameters")
        export_commands = self._set_env_vars()
        self._write_shell_script(export_commands, script_path)
        self._set_aws_parameters()
        return
